'use client';
import {useState} from "react";
type Item={ticker:string;name?:string;close:number;change:number;volume:number;score:number;momentum:number;volumeScore:number;volatility:number};
type SportLeg={eventId:string;sport:string;commence_time:string;home:string;away:string;name:string;odd:number;prob:number;books:number};
type SportsPick={combinedOdds:number;confidence:number;generatedAt:string;note:string;legs:SportLeg[]};
export default function Home(){
 const [market,setMarket]=useState<"stocks"|"crypto">("crypto"); const [items,setItems]=useState<Item[]>([]); const [sports,setSports]=useState<SportsPick|null>(null);
 const [status,setStatus]=useState("Ready. Paper mode only."); const [sportsStatus,setSportsStatus]=useState("Ready."); const [busy,setBusy]=useState(false); const [sportsBusy,setSportsBusy]=useState(false);
 async function scan(){setBusy(true);setStatus("Scanning real market data…");try{const r=await fetch("/api/scan?market="+market,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Scan failed");setItems(j.items||[]);setStatus((j.items?.length||0)+" candidates • "+j.date)}catch(e){setStatus(e instanceof Error?e.message:"Scan failed");setItems([])}finally{setBusy(false)}}
 async function sportsPick(){setSportsBusy(true);setSportsStatus("Analyzing upcoming odds…");try{const r=await fetch("/api/sports",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Sports scan failed");setSports(j.pick||null);setSportsStatus(j.pick?"Generated "+new Date(j.pick.generatedAt).toLocaleTimeString():"NO PICK — no qualifying selection in the 2.00–5.00 range.")}catch(e){setSports(null);setSportsStatus(e instanceof Error?e.message:"Sports scan failed")}finally{setSportsBusy(false)}}
 return <main className="wrap">
  <div className="head"><div><div className="title">AI Market Hunter</div><div className="sub">V1 • Short-term scanner • $100 paper capital</div></div><div className="pill">PAPER MODE</div></div>
  <div className="card"><div className="grid"><div className="stat"><div className="label">CAPITAL</div><div className="num">$100</div></div><div className="stat"><div className="label">RISK / TRADE</div><div className="num">$2 max</div></div></div><div className="notice">2% position-risk model. No real orders are sent.</div></div>
  <section className="card sports"><div className="sectionTitle">⚽ Sports Hunter</div><div className="sub">Daily research pick • total odds 2.00–5.00</div><button className="scan" onClick={sportsPick} disabled={sportsBusy}>{sportsBusy?"Analyzing…":"🎯 FIND TODAY'S PICK"}</button><div className="notice">{sportsStatus}</div>
  {sports && <div className="pick"><div className="pickHead"><div><div className="label">TOTAL ODDS</div><div className="big">@ {sports.combinedOdds.toFixed(2)}</div></div><div className="confidence"><div className="label">MODEL CONFIDENCE</div><b>{sports.confidence}%</b></div></div>{sports.legs.map((l,i)=><div className="leg" key={l.eventId+":"+l.name}><div><b>{i+1}. {l.name}</b><div className="muted">{l.home} vs {l.away}</div><div className="muted">{l.sport} • {new Date(l.commence_time).toLocaleString()}</div><div className="muted">Consensus probability: {(l.prob*100).toFixed(0)}% • {l.books} books</div></div><div className="odd">{l.odd.toFixed(2)}</div></div>)}<div className="small" style={{marginTop:9}}>{sports.note}</div></div>}
  </section>
  <div className="tabs"><button className={market==="crypto"?"on":""} onClick={()=>{setMarket("crypto");setItems([])}}>🪙 Crypto</button><button className={market==="stocks"?"on":""} onClick={()=>{setMarket("stocks");setItems([])}}>🇺🇸 Stocks</button></div>
  <button className="scan" onClick={scan} disabled={busy}>{busy?"Scanning…":"🔎 SCAN MARKET NOW"}</button><div className="notice">{status}</div>
  {items.map((x,i)=><div className="card" key={x.ticker}><div className="row"><div><b>{i+1}. {x.ticker}</b><div className="muted">{x.name||""} • close {"$"+x.close.toLocaleString(undefined,{maximumFractionDigits:8})} • day {x.change.toFixed(2)}%</div></div><div className="score">{x.score}</div></div><div className="bar"><i style={{width:x.score+"%"}}/></div><div className="grid"><div className="stat"><div className="label">MOMENTUM</div><div className="num">{x.momentum}</div></div><div className="stat"><div className="label">VOLUME</div><div className="num">{x.volumeScore}</div></div><div className="stat"><div className="label">VOLATILITY</div><div className="num">{x.volatility}</div></div><div className="stat"><div className="label">SETUP</div><div className="num">{x.score>=75?"WATCH":"WAIT"}</div></div></div><div className="small" style={{marginTop:9}}>Research signal only; no guaranteed result.</div></div>)}
  <div className="card"><b>V1 data model</b><div className="small" style={{marginTop:7}}>Massive market data and The Odds API are fetched server-side. API keys stay server-side and are never sent to the browser.</div></div>
 </main>
}